package com.appa.serverless.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "shake")
public class Shake implements Serializable {

	private static final long serialVersionUID = 1554640551199966153L;

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName = "name")
	private String name;

	@DynamoDBAttribute(attributeName = "numOrder")
	private int numOrder;

	@DynamoDBAttribute(attributeName = "price")
	private double price;

	@DynamoDBAttribute(attributeName = "discountedPrice")
	private double discountedPrice;

	@DynamoDBAttribute(attributeName = "shippingPrice")
	private double shippingPrice;

	@DynamoDBAttribute(attributeName = "qtyAvailable")
	private int qtyAvailable;

	@DynamoDBAttribute(attributeName = "description")
	private String description;

	@DynamoDBAttribute(attributeName = "imgUrl")
	private String imgUrl;

}
